use serde::{Deserialize, Serialize};

use crate::{ClipboardContent, ClipboardSource};

pub const MACCY_IGNORED_PASTEBOARD_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "Pasteboard generator type",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "net.antelle.keeweb",
];

pub const MACOS_UNIVERSAL_CLIPBOARD_TYPE: &str = "com.apple.is-remote-clipboard";

pub const WINDOWS_SENSITIVE_FORMATS: &[&str] = &[
    "Password",
    "Credential",
    "com.agilebits.onepassword",
    "KeePass",
];

pub const LINUX_SENSITIVE_MIME_TYPES: &[&str] = &[
    "x-kde-passwordManagerHint",
    "application/x-keepass-entry",
    "x-special/gnome-copied-files",
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CaptureContext {
    pub format_names: Vec<String>,
    pub source: Option<ClipboardSource>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PrivacyRules {
    pub ignored_types: Vec<String>,
    pub ignored_applications: Vec<String>,
    pub ignored_content_patterns: Vec<String>,
    pub ignore_all_apps_except_listed: bool,
}

impl PrivacyRules {
    #[must_use]
    pub fn maccy_compatible_defaults() -> Self {
        let mut ignored_types = MACCY_IGNORED_PASTEBOARD_TYPES
            .iter()
            .chain(WINDOWS_SENSITIVE_FORMATS.iter())
            .chain(LINUX_SENSITIVE_MIME_TYPES.iter())
            .map(|value| (*value).to_string())
            .collect::<Vec<_>>();
        ignored_types.sort();
        ignored_types.dedup();

        Self {
            ignored_types,
            ignored_applications: Vec::new(),
            ignored_content_patterns: Vec::new(),
            ignore_all_apps_except_listed: false,
        }
    }

    #[must_use]
    pub fn should_capture(
        &self,
        context: &CaptureContext,
        clipboard_content: &ClipboardContent,
    ) -> IgnoreDecision {
        if let Some(format_name) = self.matching_ignored_type(&context.format_names) {
            return IgnoreDecision::ignored(format!("ignored clipboard type: {format_name}"));
        }

        if let Some(source) = &context.source {
            let app_id = source.bundle_or_process_id.as_deref().unwrap_or_default();
            let app_name = source.application_name.as_deref().unwrap_or_default();
            let listed = self
                .ignored_applications
                .iter()
                .any(|ignored| ignored == app_id || ignored == app_name);

            if self.ignore_all_apps_except_listed && !listed {
                return IgnoreDecision::ignored("source application is not allow-listed");
            }

            if !self.ignore_all_apps_except_listed && listed {
                return IgnoreDecision::ignored("source application is ignored");
            }
        }

        let preview = clipboard_content.preview_text().to_lowercase();
        if let Some(pattern) = self
            .ignored_content_patterns
            .iter()
            .find(|pattern| preview.contains(&pattern.to_lowercase()))
        {
            return IgnoreDecision::ignored(format!("content matched ignored pattern: {pattern}"));
        }

        IgnoreDecision {
            capture: true,
            reason: None,
        }
    }

    #[must_use]
    pub fn with_universal_clipboard_ignored(mut self) -> Self {
        if !self
            .ignored_types
            .iter()
            .any(|value| value == MACOS_UNIVERSAL_CLIPBOARD_TYPE)
        {
            self.ignored_types
                .push(MACOS_UNIVERSAL_CLIPBOARD_TYPE.to_string());
        }
        self
    }

    fn matching_ignored_type(&self, format_names: &[String]) -> Option<String> {
        format_names
            .iter()
            .find(|format_name| {
                self.ignored_types
                    .iter()
                    .any(|ignored| ignored == *format_name)
            })
            .cloned()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IgnoreDecision {
    pub capture: bool,
    pub reason: Option<String>,
}

impl IgnoreDecision {
    fn ignored(reason: impl Into<String>) -> Self {
        Self {
            capture: false,
            reason: Some(reason.into()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn text(value: &str) -> ClipboardContent {
        ClipboardContent::Text {
            text: value.to_string(),
        }
    }

    #[test]
    fn ignores_maccy_confidential_types() {
        let rules = PrivacyRules::maccy_compatible_defaults();
        let context = CaptureContext {
            format_names: vec!["org.nspasteboard.ConcealedType".to_string()],
            source: None,
        };

        let decision = rules.should_capture(&context, &text("secret"));

        assert!(!decision.capture);
    }

    #[test]
    fn can_ignore_universal_clipboard() {
        let rules = PrivacyRules::maccy_compatible_defaults().with_universal_clipboard_ignored();
        let context = CaptureContext {
            format_names: vec![MACOS_UNIVERSAL_CLIPBOARD_TYPE.to_string()],
            source: None,
        };

        let decision = rules.should_capture(&context, &text("remote copy"));

        assert!(!decision.capture);
    }

    #[test]
    fn can_ignore_applications() {
        let mut rules = PrivacyRules::maccy_compatible_defaults();
        rules
            .ignored_applications
            .push("com.example.Secret".to_string());
        let context = CaptureContext {
            format_names: Vec::new(),
            source: Some(ClipboardSource {
                application_name: Some("Secret".to_string()),
                bundle_or_process_id: Some("com.example.Secret".to_string()),
            }),
        };

        let decision = rules.should_capture(&context, &text("secret"));

        assert!(!decision.capture);
    }

    #[test]
    fn can_ignore_content_patterns() {
        let mut rules = PrivacyRules::maccy_compatible_defaults();
        rules.ignored_content_patterns.push("token=".to_string());
        let context = CaptureContext {
            format_names: Vec::new(),
            source: None,
        };

        let decision = rules.should_capture(&context, &text("token=abc123"));

        assert!(!decision.capture);
    }
}
